/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonElement: typeof import('./src/components/components/ButtonElement.vue')['default']
    CardDocs: typeof import('./src/components/docs/CardDocs.vue')['default']
    CardElement: typeof import('./src/components/layout/CardElement.vue')['default']
    CButton: typeof import('./src/components/components/CButton.vue')['default']
    CCard: typeof import('./src/components/layout/CCard.vue')['default']
    CCheckbox: typeof import('./src/components/forms/CCheckbox.vue')['default']
    CheckboxElement: typeof import('./src/components/forms/CheckboxElement.vue')['default']
    CIcon: typeof import('./src/components/components/CIcon.vue')['default']
    CodeHightlight: typeof import('./src/components/docs/CodeHightlight.vue')['default']
    copy: typeof import('./src/components/icons/IconArrowDownCircle copy.vue')['default']
    CToggle: typeof import('./src/components/forms/CToggle.vue')['default']
    CTooltip: typeof import('./src/components/components/CTooltip.vue')['default']
    Github: typeof import('./src/components/icons/Github.vue')['default']
    IconAcademicCap: typeof import('./src/components/icons/IconAcademicCap.vue')['default']
    IconAjustmentsHorizontal: typeof import('./src/components/icons/IconAjustmentsHorizontal.vue')['default']
    IconAjustmentsVertical: typeof import('./src/components/icons/IconAjustmentsVertical.vue')['default']
    IconArchiveBox: typeof import('./src/components/icons/IconArchiveBox.vue')['default']
    IconArchiveBoxArrowDown: typeof import('./src/components/icons/IconArchiveBoxArrowDown.vue')['default']
    IconArchiveBoxXMark: typeof import('./src/components/icons/IconArchiveBoxXMark.vue')['default']
    IconArrowDown: typeof import('./src/components/icons/IconArrowDown.vue')['default']
    IconArrowDownCircle: typeof import('./src/components/icons/IconArrowDownCircle.vue')['default']
    IconArrowDownLeft: typeof import('./src/components/icons/IconArrowDownLeft.vue')['default']
    IconArrowDownOnSquare: typeof import('./src/components/icons/IconArrowDownOnSquare.vue')['default']
    IconArrowDownOnSquareStack: typeof import('./src/components/icons/IconArrowDownOnSquareStack.vue')['default']
    IconArrowDownRight: typeof import('./src/components/icons/IconArrowDownRight.vue')['default']
    IconArrowDownTray: typeof import('./src/components/icons/IconArrowDownTray.vue')['default']
    IconArrowLeftCircle: typeof import('./src/components/icons/IconArrowLeftCircle.vue')['default']
    IconBars3: typeof import('./src/components/icons/IconBars3.vue')['default']
    IconElement: typeof import('./src/components/components/IconElement.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TooltipElement: typeof import('./src/components/components/TooltipElement.vue')['default']
  }
}
