const Countries = [
    { name: "Afghanistan", iso: "af", alpha3: "AFG", numeric: "004" },
    { name: "Albania", iso: "al", alpha3: "ALB", numeric: "008" },
    { name: "Algeria", iso: "dz", alpha3: "DZA", numeric: "012" },
    { name: "Andorra", iso: "ad", alpha3: "AND", numeric: "020" },
    { name: "Angola", iso: "ao", alpha3: "AGO", numeric: "024" },
    { name: "Argentina", iso: "ar", alpha3: "ARG", numeric: "032" },
    { name: "Armenia", iso: "am", alpha3: "ARM", numeric: "051" },
    { name: "Australia", iso: "au", alpha3: "AUS", numeric: "036" },
    { name: "Austria", iso: "at", alpha3: "AUT", numeric: "040" },
    { name: "Azerbaijan", iso: "az", alpha3: "AZE", numeric: "031" },
    { name: "Bahamas", iso: "bs", alpha3: "BHS", numeric: "044" },
    { name: "Bahrain", iso: "bh", alpha3: "BHR", numeric: "048" },
    { name: "Bangladesh", iso: "bd", alpha3: "BGD", numeric: "050" },
    { name: "Barbados", iso: "bb", alpha3: "BRB", numeric: "052" },
    { name: "Belarus", iso: "by", alpha3: "BLR", numeric: "112" },
    { name: "Belgium", iso: "be", alpha3: "BEL", numeric: "056" },
    { name: "Belize", iso: "bz", alpha3: "BLZ", numeric: "084" },
    { name: "Benin", iso: "bj", alpha3: "BEN", numeric: "204" },
    { name: "Bhutan", iso: "bt", alpha3: "BTN", numeric: "064" },
    { name: "Bolivia (Plurinational State of)", iso: "bo", alpha3: "BOL", numeric: "068" },
    { name: "Bosnia and Herzegovina", iso: "ba", alpha3: "BIH", numeric: "070" },
    { name: "Botswana", iso: "bw", alpha3: "BWA", numeric: "072" },
    { name: "Brazil", iso: "br", alpha3: "BRA", numeric: "076" },
    { name: "British Indian Ocean Territory", iso: "io", alpha3: "IOT", numeric: "086" },
    { name: "Brunei Darussalam", iso: "bn", alpha3: "BRN", numeric: "096" },
    { name: "Bulgaria", iso: "bg", alpha3: "BGR", numeric: "100" },
    { name: "Burkina Faso", iso: "bf", alpha3: "BFA", numeric: "854" },
    { name: "Burundi", iso: "bi", alpha3: "BDI", numeric: "108" },
    { name: "Cabo Verde", iso: "cv", alpha3: "CPV", numeric: "132" },
    { name: "Cambodia", iso: "kh", alpha3: "KHM", numeric: "116" },
    { name: "Cameroon", iso: "cm", alpha3: "CMR", numeric: "120" },
    { name: "Canada", iso: "ca", alpha3: "CAN", numeric: "124" },
    { name: "Cayman Islands", iso: "ky", alpha3: "CYM", numeric: "136" },
    { name: "Central African Republic", iso: "cf", alpha3: "CAF", numeric: "140" },
    { name: "Chad", iso: "td", alpha3: "TCD", numeric: "148" },
    { name: "Chile", iso: "cl", alpha3: "CHL", numeric: "152" },
    { name: "China", iso: "cn", alpha3: "CHN", numeric: "156" },
    { name: "Christmas Island", iso: "cx", alpha3: "CXR", numeric: "162" },
    { name: "Colombia", iso: "co", alpha3: "COL", numeric: "170" },
    { name: "Comoros", iso: "km", alpha3: "COM", numeric: "174" },
    { name: "Congo", iso: "cg", alpha3: "COG", numeric: "178" },
    { name: "Congo (Democratic Republic of the)", iso: "cd", alpha3: "COD", numeric: "180" },
    { name: "Cook Islands", iso: "ck", alpha3: "COK", numeric: "184" },
    { name: "Costa Rica", iso: "cr", alpha3: "CRI", numeric: "188" },
    { name: "Croatia", iso: "hr", alpha3: "HRV", numeric: "191" },
    { name: "Cuba", iso: "cu", alpha3: "CUB", numeric: "192" },
    { name: "Cyprus", iso: "cy", alpha3: "CYP", numeric: "196" },
    { name: "Czech Republic", iso: "cz", alpha3: "CZE", numeric: "203" },
    { name: "Denmark", iso: "dk", alpha3: "DNK", numeric: "208" },
    { name: "Djibouti", iso: "dj", alpha3: "DJI", numeric: "262" },
    { name: "Dominica", iso: "dm", alpha3: "DMA", numeric: "212" },
    { name: "Dominican Republic", iso: "do", alpha3: "DOM", numeric: "214" },
    { name: "Ecuador", iso: "ec", alpha3: "ECU", numeric: "218" },
    { name: "Egypt", iso: "eg", alpha3: "EGY", numeric: "818" },
    { name: "El Salvador", iso: "sv", alpha3: "SLV", numeric: "222" },
    { name: "Equatorial Guinea", iso: "gq", alpha3: "GNQ", numeric: "226" },
    { name: "Eritrea", iso: "er", alpha3: "ERI", numeric: "232" },
    { name: "Estonia", iso: "ee", alpha3: "EST", numeric: "233" },
    { name: "Eswatini", iso: "sz", alpha3: "SWZ", numeric: "748" },
    { name: "Ethiopia", iso: "et", alpha3: "ETH", numeric: "231" },
    { name: "Falkland Islands", iso: "fk", alpha3: "FLK", numeric: "238" },
    { name: "Faroe Islands", iso: "fo", alpha3: "FRO", numeric: "234" },
    { name: "Fiji", iso: "fj", alpha3: "FJI", numeric: "242" },
    { name: "Finland", iso: "fi", alpha3: "FIN", numeric: "246" },
    { name: "France", iso: "fr", alpha3: "FRA", numeric: "250" },
    { name: "French Guiana", iso: "gf", alpha3: "GUF", numeric: "254" },
    { name: "French Polynesia", iso: "pf", alpha3: "PYF", numeric: "258" },
    { name: "French Southern Territories", iso: "tf", alpha3: "ATF", numeric: "260" },
    { name: "Gabon", iso: "ga", alpha3: "GAB", numeric: "266" },
    { name: "Gambia", iso: "gm", alpha3: "GMB", numeric: "270" },
    { name: "Georgia", iso: "ge", alpha3: "GEO", numeric: "268" },
    { name: "Germany", iso: "de", alpha3: "DEU", numeric: "276" },
    { name: "Ghana", iso: "gh", alpha3: "GHA", numeric: "288" },
    { name: "Gibraltar", iso: "gi", alpha3: "GIB", numeric: "292" },
    { name: "Greece", iso: "gr", alpha3: "GRC", numeric: "300" },
    { name: "Greenland", iso: "gl", alpha3: "GRL", numeric: "304" },
    { name: "Grenada", iso: "gd", alpha3: "GRD", numeric: "308" },
    { name: "Guadeloupe", iso: "gp", alpha3: "GLP", numeric: "312" },
    { name: "Guam", iso: "gu", alpha3: "GUM", numeric: "316" },
    { name: "Guatemala", iso: "gt", alpha3: "GTM", numeric: "320" },
    { name: "Guernsey", iso: "gg", alpha3: "GGY", numeric: "831" },
    { name: "Guinea", iso: "gn", alpha3: "GIN", numeric: "324" },
    { name: "Guinea-Bissau", iso: "gw", alpha3: "GNB", numeric: "624" },
    { name: "Guyana", iso: "gy", alpha3: "GUY", numeric: "328" },
    { name: "Haiti", iso: "ht", alpha3: "HTI", numeric: "332" },
    { name: "Heard Island and McDonald Islands", iso: "hm", alpha3: "HMD", numeric: "334" },
    { name: "Honduras", iso: "hn", alpha3: "HND", numeric: "340" },
    { name: "Hungary", iso: "hu", alpha3: "HUN", numeric: "348" },
    { name: "Iceland", iso: "is", alpha3: "ISL", numeric: "352" },
    { name: "India", iso: "in", alpha3: "IND", numeric: "356" },
    { name: "Indonesia", iso: "id", alpha3: "IDN", numeric: "360" },
    { name: "Iran (Islamic Republic of)", iso: "ir", alpha3: "IRN", numeric: "364" },
    { name: "Iraq", iso: "iq", alpha3: "IRQ", numeric: "368" },
    { name: "Ireland", iso: "ie", alpha3: "IRL", numeric: "372" },
    { name: "Israel", iso: "il", alpha3: "ISR", numeric: "376" },
    { name: "Italy", iso: "it", alpha3: "ITA", numeric: "380" },
    { name: "Jamaica", iso: "jm", alpha3: "JAM", numeric: "388" },
    { name: "Japan", iso: "jp", alpha3: "JPN", numeric: "392" },
    { name: "Jordan", iso: "jo", alpha3: "JOR", numeric: "400" },
    { name: "Kazakhstan", iso: "kz", alpha3: "KAZ", numeric: "398" },
    { name: "Kenya", iso: "ke", alpha3: "KEN", numeric: "404" },
    { name: "Kiribati", iso: "ki", alpha3: "KIR", numeric: "296" },
    { name: "Kuwait", iso: "kw", alpha3: "KWT", numeric: "414" },
    { name: "Kyrgyzstan", iso: "kg", alpha3: "KGZ", numeric: "417" },
    { name: "Lao People's Democratic Republic", iso: "la", alpha3: "LAO", numeric: "418" },
    { name: "Latvia", iso: "lv", alpha3: "LVA", numeric: "428" },
    { name: "Lebanon", iso: "lb", alpha3: "LBN", numeric: "422" },
    { name: "Lesotho", iso: "ls", alpha3: "LSO", numeric: "426" },
    { name: "Liberia", iso: "lr", alpha3: "LBR", numeric: "430" },
    { name: "Libya", iso: "ly", alpha3: "LBY", numeric: "434" },
    { name: "Liechtenstein", iso: "li", alpha3: "LIE", numeric: "438" },
    { name: "Lithuania", iso: "lv", alpha3: "LTU", numeric: "440" },
    { name: "Luxembourg", iso: "lu", alpha3: "LUX", numeric: "442" },
    { name: "Madagascar", iso: "mg", alpha3: "MDG", numeric: "450" },
    { name: "Malawi", iso: "mw", alpha3: "MWI", numeric: "454" },
    { name: "Malaysia", iso: "my", alpha3: "MYS", numeric: "458" },
    { name: "Maldives", iso: "mv", alpha3: "MDV", numeric: "462" },
    { name: "Mali", iso: "ml", alpha3: "MLI", numeric: "466" },
    { name: "Malta", iso: "mt", alpha3: "MLT", numeric: "470" },
    { name: "Marshall Islands", iso: "mh", alpha3: "MHL", numeric: "584" },
    { name: "Martinique", iso: "mq", alpha3: "MTQ", numeric: "474" },
    { name: "Mauritania", iso: "mr", alpha3: "MRT", numeric: "478" },
    { name: "Mauritius", iso: "mu", alpha3: "MUS", numeric: "480" },
    { name: "Mayotte", iso: "yt", alpha3: "MYT", numeric: "175" },
    { name: "Mexico", iso: "mx", alpha3: "MEX", numeric: "484" },
    { name: "Micronesia (Federated States of)", iso: "fm", alpha3: "FSM", numeric: "583" },
    { name: "Moldova (the Republic of)", iso: "md", alpha3: "MDA", numeric: "498" },
    { name: "Monaco", iso: "mc", alpha3: "MCO", numeric: "492" },
    { name: "Mongolia", iso: "mn", alpha3: "MNG", numeric: "496" },
    { name: "Montenegro", iso: "me", alpha3: "MNE", numeric: "499" },
    { name: "Montserrat", iso: "ms", alpha3: "MSR", numeric: "500" },
    { name: "Morocco", iso: "ma", alpha3: "MAR", numeric: "504" },
    { name: "Mozambique", iso: "mz", alpha3: "MOZ", numeric: "508" },
    { name: "Myanmar", iso: "mm", alpha3: "MMR", numeric: "104" },
    { name: "Namibia", iso: "na", alpha3: "NAM", numeric: "516" },
    { name: "Nauru", iso: "nr", alpha3: "NRU", numeric: "520" },
    { name: "Nepal", iso: "np", alpha3: "NPL", numeric: "524" },
    { name: "Netherlands", iso: "nl", alpha3: "NLD", numeric: "528" },
    { name: "New Caledonia", iso: "nc", alpha3: "NCL", numeric: "540" },
    { name: "New Zealand", iso: "nz", alpha3: "NZL", numeric: "554" },
    { name: "Nicaragua", iso: "ni", alpha3: "NIC", numeric: "558" },
    { name: "Niger", iso: "ne", alpha3: "NER", numeric: "562" },
    { name: "Nigeria", iso: "ng", alpha3: "NGA", numeric: "566" },
    { name: "Niue", iso: "nu", alpha3: "NIU", numeric: "570" },
    { name: "Norfolk Island", iso: "nf", alpha3: "NFK", numeric: "574" },
    { name: "North Macedonia", iso: "mk", alpha3: "MKD", numeric: "807" },
    { name: "Northern Mariana Islands", iso: "mp", alpha3: "MNP", numeric: "580" },
    { name: "Norway", iso: "no", alpha3: "NOR", numeric: "578" },
    { name: "Oman", iso: "om", alpha3: "OMN", numeric: "512" },
    { name: "Pakistan", iso: "pk", alpha3: "PAK", numeric: "586" },
    { name: "Palau", iso: "pw", alpha3: "PLW", numeric: "585" },
    { name: "Palestine, State of", iso: "ps", alpha3: "PSE", numeric: "275" },
    { name: "Panama", iso: "pa", alpha3: "PAN", numeric: "591" },
    { name: "Papua New Guinea", iso: "pg", alpha3: "PNG", numeric: "598" },
    { name: "Paraguay", iso: "py", alpha3: "PRY", numeric: "600" },
    { name: "Peru", iso: "pe", alpha3: "PER", numeric: "604" },
    { name: "Philippines", iso: "ph", alpha3: "PHL", numeric: "608" },
    { name: "Pitcairn", iso: "pn", alpha3: "PCN", numeric: "612" },
    { name: "Poland", iso: "pl", alpha3: "POL", numeric: "616" },
    { name: "Portugal", iso: "pt", alpha3: "PRT", numeric: "620" },
    { name: "Puerto Rico", iso: "pr", alpha3: "PRI", numeric: "630" },
    { name: "Qatar", iso: "qa", alpha3: "QAT", numeric: "634" },
    { name: "Réunion", iso: "re", alpha3: "REU", numeric: "638" },
    { name: "Romania", iso: "ro", alpha3: "ROU", numeric: "642" },
    { name: "Russian Federation", iso: "ru", alpha3: "RUS", numeric: "643" },
    { name: "Rwanda", iso: "rw", alpha3: "RWA", numeric: "646" },
    { name: "Saint Barthélemy", iso: "bl", alpha3: "BLM", numeric: "652" },
    { name: "Saint Helena, Ascension and Tristan da Cunha", iso: "sh", alpha3: "SHN", numeric: "654" },
    { name: "Saint Kitts and Nevis", iso: "kn", alpha3: "KNA", numeric: "659" },
    { name: "Saint Lucia", iso: "lc", alpha3: "LCA", numeric: "662" },
    { name: "Saint Martin (French part)", iso: "mf", alpha3: "MAF", numeric: "663" },
    { name: "Saint Pierre and Miquelon", iso: "pm", alpha3: "SPM", numeric: "666" },
    { name: "Saint Vincent and the Grenadines", iso: "vc", alpha3: "VCT", numeric: "670" },
    { name: "Samoa", iso: "ws", alpha3: "WSM", numeric: "882" },
    { name: "San Marino", iso: "sm", alpha3: "SMR", numeric: "674" },
    { name: "Sao Tome and Principe", iso: "st", alpha3: "STP", numeric: "678" },
    { name: "Saudi Arabia", iso: "sa", alpha3: "SAU", numeric: "682" },
    { name: "Senegal", iso: "sn", alpha3: "SEN", numeric: "686" },
    { name: "Serbia", iso: "rs", alpha3: "SRB", numeric: "688" },
    { name: "Seychelles", iso: "sc", alpha3: "SYC", numeric: "690" },
    { name: "Sierra Leone", iso: "sl", alpha3: "SLE", numeric: "694" },
    { name: "Singapore", iso: "sg", alpha3: "SGP", numeric: "702" },
    { name: "Sint Maarten (Dutch part)", iso: "sx", alpha3: "SXM", numeric: "534" },
    { name: "Slovakia", iso: "sk", alpha3: "SVK", numeric: "703" },
    { name: "Slovenia", iso: "si", alpha3: "SVN", numeric: "705" },
    { name: "Solomon Islands", iso: "sb", alpha3: "SLB", numeric: "090" },
    { name: "Somalia", iso: "so", alpha3: "SOM", numeric: "706" },
    { name: "South Africa", iso: "za", alpha3: "ZAF", numeric: "710" },
    { name: "South Georgia and the South Sandwich Islands", iso: "gs", alpha3: "SGS", numeric: "239" },
    { name: "South Sudan", iso: "ss", alpha3: "SSD", numeric: "728" },
    { name: "Spain", iso: "es", alpha3: "ESP", numeric: "724" },
    { name: "Sri Lanka", iso: "lk", alpha3: "LKA", numeric: "144" },
    { name: "Sudan", iso: "sd", alpha3: "SDN", numeric: "729" },
    { name: "Suriname", iso: "sr", alpha3: "SUR", numeric: "740" },
    { name: "Svalbard and Jan Mayen", iso: "sj", alpha3: "SJM", numeric: "744" },
    { name: "Sweden", iso: "se", alpha3: "SWE", numeric: "752" },
    { name: "Switzerland", iso: "ch", alpha3: "CHE", numeric: "756" },
    { name: "Syrian Arab Republic", iso: "sy", alpha3: "SYR", numeric: "760" },
    { name: "Taiwan (Province of China)", iso: "tw", alpha3: "TWN", numeric: "158" },
    { name: "Tajikistan", iso: "tj", alpha3: "TJK", numeric: "762" },
    { name: "Tanzania, United Republic of", iso: "tz", alpha3: "TZA", numeric: "834" },
    { name: "Thailand", iso: "th", alpha3: "THA", numeric: "764" },
    { name: "Timor-Leste", iso: "tl", alpha3: "TLS", numeric: "626" },
    { name: "Togo", iso: "tg", alpha3: "TGO", numeric: "768" },
    { name: "Tokelau", iso: "tk", alpha3: "TKL", numeric: "772" },
    { name: "Tonga", iso: "to", alpha3: "TON", numeric: "776" },
    { name: "Trinidad and Tobago", iso: "tt", alpha3: "TTO", numeric: "780" },
    { name: "Tunisia", iso: "tn", alpha3: "TUN", numeric: "788" },
    { name: "Turkey", iso: "tr", alpha3: "TUR", numeric: "792" },
    { name: "Turkmenistan", iso: "tm", alpha3: "TKM", numeric: "795" },
    { name: "Turks and Caicos Islands", iso: "tc", alpha3: "TCA", numeric: "796" },
    { name: "Tuvalu", iso: "tv", alpha3: "TUV", numeric: "798" },
    { name: "Uganda", iso: "ug", alpha3: "UGA", numeric: "800" },
    { name: "Ukraine", iso: "ua", alpha3: "UKR", numeric: "804" },
    { name: "United Arab Emirates", iso: "ae", alpha3: "ARE", numeric: "784" },
    { name: "United Kingdom of Great Britain and Northern Ireland", iso: "gb", alpha3: "GBR", numeric: "826" },
    { name: "United States of America", iso: "us", alpha3: "USA", numeric: "840" },
    { name: "Uruguay", iso: "uy", alpha3: "URY", numeric: "858" },
    { name: "Uzbekistan", iso: "uz", alpha3: "UZB", numeric: "860" },
    { name: "Vanuatu", iso: "vu", alpha3: "VUT", numeric: "548" },
    { name: "Venezuela (Bolivarian Republic of)", iso: "ve", alpha3: "VEN", numeric: "862" },
    { name: "Viet Nam", iso: "vn", alpha3: "VNM", numeric: "704" },
    { name: "Western Sahara", iso: "eh", alpha3: "ESH", numeric: "732" },
    { name: "Yemen", iso: "ye", alpha3: "YEM", numeric: "887" },
    { name: "Zambia", iso: "zm", alpha3: "ZMB", numeric: "894" },
    { name: "Zimbabwe", iso: "zw", alpha3: "ZWE", numeric: "716" },
    { name: "Anguilla", iso: "ai", alpha3: "AIA", numeric: "660" },
    { name: "Antarctica", iso: "aq", alpha3: "ATA", numeric: "010" },
    { name: "Aruba", iso: "aw", alpha3: "ABW", numeric: "533" },
    { name: "Bermuda", iso: "bm", alpha3: "BMU", numeric: "060" },
    { name: "Bonaire, Sint Eustatius and Saba", iso: "bq", alpha3: "BES", numeric: "535" },
    { name: "Bouvet Island", iso: "bv", alpha3: "BVT", numeric: "074" },
    { name: "Cocos (Keeling) Islands", iso: "cc", alpha3: "CCK", numeric: "166" },
    { name: "United States Minor Outlying Islands", iso: "um", alpha3: "UMI", numeric: "581" },
    { name: "Virgin Islands (British)", iso: "vg", alpha3: "VGB", numeric: "092" },
    { name: "Virgin Islands (U.S.)", iso: "vi", alpha3: "VIR", numeric: "850" },
    { name: "Wallis and Futuna", iso: "wf", alpha3: "WLF", numeric: "876" }
];

export default Countries;
